### ISSUE TITLE
Feedback for Milestone 2

### ISSUE THREAD

**Issue by jackattackyang** [UBC-MDS/DSCI_532_Wine_Betty_Milos#16]
Pro
- Layout is clean and color scheme is easy on the eyes
- I like that all the data columns are incorporated, no features are lost

Improvements
- [ ] Make pricing column more responsive
- [ ] Change rating from 80-100 to 0-20 because lowest wine rating is 80, to make everything relative
- [ ] Expand desired price range to all the data (up to the most expensive wine range)

**Comment by bettybhzhou** [comment]
Thanks for catching the bug in our price range slider! We ended up sticking with the 80-100 range and just made a note that the min rating is 80.
